CREATE TABLE IF NOT EXISTS patient (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address       VARCHAR(255) NOT NULL,
    date_of_birth VARCHAR(255) NOT NULL,
    first_name    VARCHAR(255) NOT NULL,
    gender        VARCHAR(255) NOT NULL,
    last_name     VARCHAR(255) NOT NULL,
    phone         VARCHAR(255)
);

INSERT INTO patient (id, address, date_of_birth, first_name, gender, last_name, phone)
OVERRIDING SYSTEM VALUE VALUES
(12, '1 Brookside St', '1966-12-31', 'Test', 'F', 'TestNone',       '1002223333'),
(13, '2 High St',      '1945-06-24', 'Test', 'M', 'TestBorderline', '2003334444'),
(14, '3 Club Road',    '2004-06-18', 'Test', 'M', 'TestInDanger',   '0000000000'),
(15, '4 Valley Dr',    '2002-06-28', 'Test', 'F', 'TestEarlyOnset', '4005556666')
ON CONFLICT (id) DO NOTHING;

-- Advance the sequence past the seeded IDs so new inserts don't collide
SELECT setval(pg_get_serial_sequence('patient', 'id'), (SELECT MAX(id) FROM patient));

-- TODO: profiles for dev environment