spring.application.name=notes
server.port=8082
spring.data.mongodb.uri=mongodb+srv://annerutecki_db_user:Oc7b41dZTHDRFnhT@cluster0.3ltvyey.mongodb.net/Cluster0
jwt.secret=thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
jwt.expiration=3600000
