services:
  risk:
    image: medilabo-risk
    container_name: risk-app
    ports:
      - "8083:8083"
    environment:
      DEMOGRAPHICS_URL: http://host.docker.internal:8081
      NOTES_URL: http://host.docker.internal:8082
      JWT_SECRET: thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
      JWT_EXPIRATION: 3600000
    extra_hosts:
      - "host.docker.internal:host-gateway"
