spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: notes-service
              uri: http://notes:8082
              predicates:
                - Path=/api/notes/**
                - Method=GET,POST,PUT,DELETE,OPTIONS

            - id: risk-service
              uri: http://risk:8083
              predicates:
                - Path=/api/risk/**
                - Method=GET,OPTIONS

            - id: demographics
              uri: http://demographics:8081
              predicates:
                - Path=/api/**
                - Method=GET,POST,PUT,DELETE,OPTIONS
