services:
  notes:
    image: medilabo-notes
    container_name: notes-app
    ports:
      - "8082:8082"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://annerutecki_db_user:Oc7b41dZTHDRFnhT@cluster0.3ltvyey.mongodb.net/Cluster0
      JWT_SECRET: thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
      JWT_EXPIRATION: 3600000
